services:
  app:
    image: the-quran-next
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    volumes:
      - quran_app:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
volumes:
  quran_app:
  quran_data:
# version: "3.8"
# services:
#   app:
#     image: the-quran-next
#     build:
#       context: ./
#       target: dev
#       dockerfile: Dockerfile
#     volumes:
#       - .:/app
#       - /app/node_modules
#       - /app/.next
#       - /app/prisma
#     ports:
#       - "3000:3000"
